remote_theme: daattali/beautiful-jekyll@6.0.1

# Name of website
title: Salus Games

# Your name to show in the footer
author: Salus Games

# Site description for meta tags
description: "Salus Games - Independent puzzle game developer based in Cornwall, UK. Creators of Hexa and Layers, available on Steam."

# Colours
navbar-col: "#262a2e"
navbar-text-col: "#e4e6eb"
navbar-border-col: "#ffffff"
page-col: "#343a40"
text-col: "#e4e6eb"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#262a2e"
footer-text-col: "#e4e6eb"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Analytics
gtag: "G-RYF46YSCLL"

# Nav Menu
navbar-links:
  Games:
    - Layers: "layers"
    - Hexa: "hexa"
  About: "about"

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/salus-games-logo.png"

post_search: true

site-css:
  - "/css/imageslider.css"
  - "/css/custom.css"

social-network-links:
  email: "support@salusgames.com"
  github: salusgames
  twitter: salusgames

permalink: /:year-:month-:day-:title/