# Site settings
title: Salus Games
description: Description
baseurl: "/"
url: "https://salusgames.github.io/" 

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /:year/:month/:day/:title/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
include: ["_pages"]
plugins:
  - jekyll-feed
  - jekyll-include-cache

